### ISSUE TITLE
Loss is not converge

### ISSUE THREAD

**Issue by fred206968** [arthurdouillard/CVPR2021_PLOP#10]
While I am reimplementing your code with your setting given in the scripts folder, I found the results are a bit lower than the paper results(2%-5%). When I check the tensorboard for the loss, I found that from step 1, the loss is not converging and some of them are NaN. 
![image](https://user-images.githubusercontent.com/55863008/119439805-b450dc00-bd55-11eb-8f11-50dbfaa97c93.png)

Have you ever run into this problem?

**Comment by arthurdouillard** [comment]
No I don't have this problem, but I'm going to need more info:
- what is the dataset? VOC?
- what is the setting? 15-5? 15-1?
- did you use mixed precision? It seems (see #8) that without the loss scaling of apex you may encounter problems

It can also helps if you give me the complete command or script used.

**Comment by fred206968** [comment]
I use voc dataset and the task 19-1 and run the plop_19-1.sh for the implementation. The command line keeps outputting the warning message as following:
![image](https://user-images.githubusercontent.com/55863008/120439864-9585c180-c3b5-11eb-83f3-35652a6edfd1.png)
The loss is nan starting from step1

**Comment by arthurdouillard** [comment]
I'm currently rerunning this script, I don't have much gpus right now, so I may have results in a few days. But I've just rerunned a quick iteration with one epoch per step and I didn't have your problem.

This setting (voc 19-1) has already been reproduced by others (with even better results), so I suspect there is problem on your side.

What are the versions of torch, torchvision, apex, and cuda?

**Comment by fred206968** [comment]
Problem Solved. Thanks

**Comment by arthurdouillard** [comment]
What was the problem? 

Your solution may help others that encounter the same problem.

**Comment by fred206968** [comment]
The problem is I install the apex without cpp extension

**Comment by arthurdouillard** [comment]
Good to know, thanks!
