### ISSUE TITLE
How to prepare the data?

### ISSUE THREAD

**Issue by zhangchbin** [arthurdouillard/CVPR2021_PLOP#2]
I noticed that there are some differences in data.
How can I prepare the data?

**Comment by arthurdouillard** [comment]
You don't really have to prepare anything per se. For VOC and ADE you can use Cermelli's script which are in the `data` folder. For Cityscapes I've simply download the link they gave me (you need to send some request to Cityscapes org), and unzip all compressed files.

Then you need to specify in command line, which dataset you want and what is the DATA_ROOT.

**Comment by zhangchbin** [comment]
Hi, this is my 'data' folder
![image](https://user-images.githubusercontent.com/35215543/111484459-be13fd00-8770-11eb-9e2f-7b45a1903601.png).
DATA_ROOT is 'data/'

**Comment by arthurdouillard** [comment]
Then what? Do you have a specific error? I'm not sure what your problem is...

**Comment by zhangchbin** [comment]
Thank you very much! I have solved this problem!

**Comment by arthurdouillard** [comment]
Great! I'll to add more explanation in the readme if I can make it clearer.

Don't hesitate to open a new issue, if you have other problems :)
