### ISSUE TITLE
predict and visualization

### ISSUE THREAD

**Issue by Liuhao-128** [arthurdouillard/CVPR2021_PLOP#27]
**Describe the bug**
Hi , I have one question about how to predict a picture when finish the training stage, in other words, how to visualize the segmentation results in your code.
I have written a simple visualization .py  file, but when I load the model , I found that the model did not load successfully.
If it's convenient, I would appreciate it if  you could share your predict code. 
We look forward to your answer， thanks

**To Reproduce**

Dataset: voc-2012
Setting: 19-1
Command used or script used:

**Expected behavior**

**Additional context**

**Comment by arthurdouillard** [comment]
Hey, thank for youur interest in our work :)

Please look at this issue https://github.com/arthurdouillard/CVPR2021_PLOP/issues/17, I think it is what you're looking for right?

**Comment by Liuhao-128** [comment]
thanks for your answer. 
actually,  today I also setting the args.visulization =True and samples_number =10, the visualization results of the val_dataset on the tensorboard are available, 
I will try this code（issue https://github.com/arthurdouillard/CVPR2021_PLOP/issues/17） as soon as possible, thanks again!

**Comment by Liuhao-128** [comment]
Hi, I have run the predict.py file in issue #17,  and get the results, the detail in the attachment, but i have some questions about that code.
1 this code confused me --old_model.module.in_eval = True, I commented directly since there is no old module to import or instance.
2 the Target part has an error  in this code: --target[~mask] = 0 , and 
i don't understand the function of this part.  if i want visualize the final validation on voc dataset in task 19-1, Could you explain it to me how to setting the , thanks , the detail in attachment picture--error code



![error-code](https://user-images.githubusercontent.com/68798657/155833475-b4f241c1-f449-4a09-9169-d51c97fa5583.png)

**Comment by arthurdouillard** [comment]
Hum, it depends on your version of pytorch I think for the mask.

Try casting the mask as boolean (`target[~mask.bool()] = 0`) or byte (`target[~mask.byte()] = 0`).

Try this command:

```bash
python3 viz.py --dataset voc --task 19-1 --step 1 --ckpt my_model.pth --indexes 0 100 500 1000 1245 1277 1330 1355 1425 1447 --name my_name
```

I think it should work :)
