### ISSUE TITLE
About apex=0.1

### ISSUE THREAD

**Issue by congwei45** [arthurdouillard/CVPR2021_PLOP#28]
I config the same pytorch, torchvision and cuda version with you, however, I can not install apex=0.1. Can you tell you how to install it in detail? Thank you!

**Comment by arthurdouillard** [comment]
Hello, thank for your interest in our work :)

I have written this in the readme:

```bash
conda install -y pytorch torchvision cudatoolkit=10.2 -c pytorch
cd apex
pip3 install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

Have you tried that? If it doesn't work, can you provide the error message?

**Comment by congwei45** [comment]
![image](https://user-images.githubusercontent.com/93335349/155908467-9cab1918-39ea-447b-a3e6-8982c590ff14.png)

**Comment by arthurdouillard** [comment]
I cannot tell you anything given that. Give the full logs output as written in the error message.

**Comment by arthurdouillard** [comment]
If you found your error @congwei45, can you please tell me so I can help better future users?

**Comment by yesokyin** [comment]
> I config the same pytorch, torchvision and cuda version with you, however, I can not install apex=0.1. Can you tell you how to install it in detail? Thank you!

It is possible that the server version is relatively high.
