### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by congwei45** [arthurdouillard/CVPR2021_PLOP#29]
As you write in readme "Since the pretrained are made on multiple-gpus, they contain a prefix "module." in each key of the network. Please, be sure to remove them to be compatible with this code (simply rename them using key = key[7:]) (if you're working on single gpu). "

If I use 2 gpus, i.e., --nproc_per_node=2, do I still need to modify the pretrained network?

**Comment by arthurdouillard** [comment]
I don't think you need to do that in that case.

**Comment by congwei45** [comment]
Thanks for your answer!
