### ISSUE TITLE
why there are attentions in ResNet?

### ISSUE THREAD

**Issue by zhaoedf** [arthurdouillard/CVPR2021_PLOP#30]
![image](https://user-images.githubusercontent.com/48846150/158588697-bad25a91-25e6-4d7f-b263-f86c8184bcd9.png)

why? at first i thought this might be related to inplace_abn, then i checked the paper of inplace_abn, found no relevant info.

**Comment by arthurdouillard** [comment]
What I call `attentions` there is simply the ultimate feature maps of a resnet block (`mod*`) just before the ReLU.

For here `x = ReLU(att)`.

**Comment by zhaoedf** [comment]
> What I call `attentions` there is simply the ultimate feature maps of a resnet block (`mod*`) just before the ReLU.
> 
> For here `x = ReLU(att)`.

oh i understood, thanks
