### ISSUE TITLE
 potential bug in datasets.utils (won't change behavior)

### ISSUE THREAD

**Issue by zhaoedf** [arthurdouillard/CVPR2021_PLOP#31]
**Describe the bug**
 potential bug (won't change behavior)

![image](https://user-images.githubusercontent.com/48846150/158774168-9336f101-dd48-47fe-8ce3-a511fc0d1b07.png)

should it be the "c" variable in the two red rectangles? though "cls" variable won't cause any bugs since the lambda can capture local variables, but this could be confused to some other people.

**Comment by arthurdouillard** [comment]
Yes, you're right, that's something I also found in the original codebase but got to lazy to fix ahah

I'll try to find time today, to fix that

**Comment by zhaoedf** [comment]
> Yes, you're right, that's something I also found in the original codebase but got to lazy to fix ahah
> 
> I'll try to find time today, to fix that

quick reply! thanks
