### ISSUE TITLE
what is label "255" in target ?

### ISSUE THREAD

**Issue by zhaoedf** [arthurdouillard/CVPR2021_PLOP#32]
![image](https://user-images.githubusercontent.com/48846150/159487401-0dacb74e-bf48-4491-9b2a-71b6d4214826.png)

label "255" seem like some kind of edge to me? what is it for?

**Comment by arthurdouillard** [comment]
It's the "unknown" label commonly used in segmentation. This value is discarded both a train- and test-time.

Look at the `ignore_index` in the cross-entropy: https://github.com/arthurdouillard/CVPR2021_PLOP/blob/main/train.py#L76

**Comment by zhaoedf** [comment]
> It's the "unknown" label commonly used in segmentation. This value is discarded both a train- and test-time.
> 
> Look at the `ignore_index` in the cross-entropy: https://github.com/arthurdouillard/CVPR2021_PLOP/blob/main/train.py#L76

dose this '255' exists in the original voc dataset? why not assign a specific label to these pixels or set it as bg?

you said this is commonly used in segmentation, where can i find more info? thx.

**Comment by arthurdouillard** [comment]
It exists in the original VOC dataset. You could consider it as bg, but usually that's not-well defined pixels on the boundaries, so everyone discard it.

Hum, I'm not sure about ref for that, just look at any dataset, they all have that

**Comment by zhaoedf** [comment]
> It exists in the original VOC dataset. You could consider it as bg, but usually that's not-well defined pixels on the boundaries, so everyone discard it.
> 
> Hum, I'm not sure about ref for that, just look at any dataset, they all have that

i understood, thanks!
