### ISSUE TITLE
Filtering images

### ISSUE THREAD

**Issue by prabhuteja12** [arthurdouillard/CVPR2021_PLOP#4]
Hi,

I'm looking at your code to `filter_images` in 
[utils.py](https://github.com/arthurdouillard/CVPR2021_PLOP/blob/main/dataset/utils.py#L32). I see that the arguments to the lambda function are not used at all. 

```python
fil = lambda c: any(x in labels for x in cls)
```

and I think the filtering codes can be simplified to `np.intersect1d`, right?

Is this correct?

**Comment by arthurdouillard** [comment]
Hey,

This is snippet is from the code of https://github.com/fcdl94/MiB.

Yes, the lambda argument is not used, but because of late binding of the lambda the code still works. Sure intersect can probably work too.

You can do that and check that the generated indexes are the same :)

**Comment by prabhuteja12** [comment]
Cool. Thanks!
