### ISSUE TITLE
Question about how to install inplace-abn

### ISSUE THREAD

**Issue by FFFFlamingo** [arthurdouillard/CVPR2021_PLOP#40]
Thanks for your great work!
How do I install the corresponding version of Inplace-ABN on Windows?
'Pip install inplace-abn' doesn't work.Neither does 'git clone' the package and then 'python setup.py install'.
I look forward to your reply.

**Comment by arthurdouillard** [comment]
Hi, thanks for the kind words.

I have no idea, I haven't touch a windows for years tbh. You should ask the authors of inplace-abn directly at: https://github.com/mapillary/inplace_abn
