### ISSUE TITLE
环境报错

### ISSUE THREAD

**Issue by xyf159** [arthurdouillard/CVPR2021_PLOP#6]
请问你的CUDA版本是多岁，readme中torch1.7.1h和torchvision0.4.0不匹配，我运行一直报错。

**Comment by arthurdouillard** [comment]
Ah! I'm 很高兴 that my poor skill in Chinese help me here, 我明白你说话的意思了

The version I'm currently using (but previous version as written in the readme should have work) is:

CUDA: 10.2
torch: 1.8.1+cu102
torchvision: 0.9.1+cu102

再见,

**Comment by xyf159** [comment]
Thank you for your reply, I wish you good health and look forward to your future work!&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arthurdouillard/CVPR2021_PLOP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 晚上8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arthurdouillard/CVPR2021_PLOP] 环境报错 (#6)





 
Ah! I'm 很高兴 that my poor skill in Chinese help me here, 我明白你说话的意思了
 
The version I'm currently using (but previous version as written in the readme should have work) is:
 
CUDA: 10.2
 torch: 1.8.1+cu102
 torchvision: 0.9.1+cu102
 
再见,
